name: ci.python

on:
  pull_request:
    branches:
      - main
    paths:
      - 'phasetelemetry/**'
      - 'tests/**'
      - '.github/workflows/ci.python.yaml'
  push:
    branches:
      - main
    paths:
      - 'phasetelemetry/**'
      - 'tests/**'
      - '.github/workflows/ci.python.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.11]
      fail-fast: false
    permissions:
      contents: read
    env:
      PYTHONPATH: ${{ github.workspace }}/phasetelemetry
      TOX_WORK_DIR: ${{ github.workspace }}/.tox
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup python
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      # Setup tox
      - run: pip install -r requirements.txt
      - run: mkdir -p ${{ env.TOX_WORK_DIR }}
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ env.TOX_WORK_DIR }}
          key: phasetelemetry-tox-${{ matrix.python-version }}-${{ hashFiles('tox.ini') }}
          restore-keys: |
            phasetelemetry-tox-${{ matrix.python-version }}-

      # Run tests
      - run: |
          tox_target_env=py${PYTHON_VERSION//./}
          tox run -e $tox_target_env
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      # Check formatting
      - run: |
          tox -e format
          if ! git diff --exit-code; then
            echo "Not formatted."
            exit 1
          fi
